= Cyberismo base module

== Copyright

Copyright © Cyberismo Ltd and contributors 2024

== License and trademark policy

This is free content: you can redistribute it and/or modify it under the terms of the Creative Commons Attribution-ShareAlike 4.0 International Public License.

The use of Cyberismo trademark is governed by the Cyberismo open source trademark policy. See separate file TRADEMARK.adoc.

This content is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the Creative Commons Attribution-ShareAlike 4.0 International Public License in the separate LICENSE file for more details.

== Contributing

See separate file CONTRIBUTING.

== About the Cyberismo base module

The Cyberismo base module contains the basic building blocks common to many Cyberismo project types. This includes card types such as

* controlled document
* decision
* page
* task

along with their fundamental field types, link types, templates and workflows.

== Using the Cyberismo base module

In order to use the base module content in your Cyberismo project, take the following steps:

* Clone this repository alongside your Cyberismo project
* Change to your project directory
* Import the base module content with

    cyberismo import module ../module-base

For more details, see https://docs.cyberismo.com[Cyberismo documentation].

